# Имя лог-файла (если оставить пустым, то логи будут уходить в консоль)
log-filename: ''

# Адрес (порт) сервиса http
http-addr: ':8080'

# Адрес центрифуги по умолчанию (можно также указать в запросе)
centrifugo-url: 'http://localhost/Centrifugo'